app_abtest/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'app_abtest'
urlpatterns = [

    # DASHBOARD
    path('dashboard/', views.ABTestListDashboardView, name='abtest_list_dashboard'),
    path('dashboard/test/<int:pk>/', views.ABTestDetailDashboardView, name='abtest_results'),

    # TESTER
    path('<int:pk>/', views.ABTestDetailTesterView, name='abtest_tester_detail'),
    path('maacih/', views.ABTestThanksView, name='abtest_thanks'),
    
]

admin.site.site_header = 'MamiUX Dashboard'

mamiux/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from app_abtest import views
from django.conf.urls.static import static
from django.views.static import serve


handler404 = 'app_abtest.views.error_404_view'
urlpatterns = [

    # STATIC PAGE
    path('', views.ABTestStaticHomepageView, name='abtest_static_homepage'),
    path('thanks/', views.ABTestThanksView, name='abtest_static_thanks'),

    #MAIN
    path('admin/', admin.site.urls),
    path('abtest/', include('app_abtest.urls', namespace='abtest')),

    #APP
    #path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('allauth.urls')),
    path('captcha/', include('captcha.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_abtest/models.py
from django.db import models
from django.urls import reverse
from app_user.models import Tester
from taggit.managers import TaggableManager


class Design(models.Model):

    """
    Design/Materi Testing Model
    """
    
    id = models.AutoField(
        primary_key = True,
        unique = True
    )

    design_title = models.CharField(
        verbose_name = "A/B Testing Title",
        max_length = 225,
        null = False,
        blank = False
    )

    design_image_a = models.ImageField(
        upload_to = 'images/%Y/%m/%d',
        null = True,
        blank = True
    )

    design_image_b = models.ImageField(
        upload_to ='images/%Y/%m/%d',
        null = True,
        blank = True
    )

    is_published = models.BooleanField(
        default = False
    )

    is_created = models.DateTimeField(
        auto_now_add = True,
        null = True,
        blank = True
    )

    is_modified = models.DateTimeField(
        auto_now = True,
        null = True,
        blank = True
    )

    tags = TaggableManager()

    class Meta:
        verbose_name_plural = "Design Testing Materials"


    def __str__(self):
        return str(self.design_title)


class DesignComment(models.Model):

    """
    AB Test Comment Model
    """

    AB = (
        ('a', 'A'), 
        ('b', 'B')
    )

    design_abtest_tester_user = models.ForeignKey(
        Tester,
        verbose_name = "Tester user",
        related_name = 'tester_user_hook',
        null = True,
        blank = True,
        on_delete = models.CASCADE
    )

    design_abtest_tester_email = models.EmailField(
        verbose_name = "Email",
        null = True,
        blank = True,
        max_length = 225,
    )

    design_abtest_title = models.ForeignKey(
        Design, 
        verbose_name = "Testing Title",
        related_name = "testing_title",
        null = True,
        blank = True,
        on_delete = models.CASCADE
    )

    design_abtest_choice = models.CharField(
        choices = AB,
        verbose_name = "Pilih A/B?",
        help_text = 'Mana yang menurut kamu paling mudah digunakan? A atau B?',
        null = True,
        blank = False,
        max_length=1
    )

    design_abtest_comment = models.TextField(
        verbose_name = "Komentar",
        help_text = 'Kenapa kamu memilih pilihan itu? Bisa coba tolong jelaskan? <b>(Minimal 30 karakter)</b>',
        null = False,
        blank = False
    )

    is_published = models.BooleanField(
        default = False
    )

    is_created = models.DateTimeField(
        auto_now_add = True,
        null = True,
        blank = True
    )

    is_modified = models.DateTimeField(
        auto_now = True,
        null = True,
        blank = True
    )

    # Limit user only can post once
    # def save(self, *args, **kwargs):
    #     if self.__class__.objects.filter(design_abtest_tester_user=self.design_abtest_tester_user).count()>=1:
    #         return None
    #     return super().save(*args, **kwargs)
    

    class Meta:
        verbose_name_plural = "Test Results"

    def __str__(self):
        return str(self.design_abtest_tester_user)

app_abtest/forms.py
from django import forms
from .models import DesignComment
from captcha.fields import CaptchaField


class ABTestCommentModelForm(forms.ModelForm):

    """
    Comment Form
    """

    captcha = CaptchaField()
    class Meta:
        model = DesignComment
        fields = (
            'design_abtest_choice',
            'design_abtest_comment',
        )
        exclude = [ 'design_abtest_title', 'design_abtest_tester_user', "design_abtest_tester_email", 'is_published']
        widgets = {
            'design_abtest_tester_email': forms.HiddenInput(),
            'design_abtest_title': forms.HiddenInput(),
            'design_abtest_tester_user': forms.HiddenInput(),
            'is_published': forms.HiddenInput(),
        }

app_abtest/views.py
from datetime import datetime
from app_user.models import Tester
from django.db.models import Count
from django.http import HttpResponseRedirect
from .forms import ABTestCommentModelForm
from .models import Design, DesignComment
from django.http import Http404
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger



# STATIC PAGE VIEWS -----------------

def ABTestStaticHomepageView(request):

    """
    Render Homepage Static
    :param request:
    :return:
    """

    template = "app_abtest/static/abtest_static_homepage.html"
    return render(request, template)


def ABTestThanksView(request):
    
    """
    Render Thanks Static
    :param request:
    :return:
    """
    
    template = "app_abtest/static/abtest_static_thanks.html"
    return render(request, template)


# CUSTOM ERROR PAGE

def error_404_view(request, exception):
    return render(request,'app_abtest/static/404.html', locals())

# ---------------------------


# DASHBOARD VIEWS -----------------

@login_required
def ABTestListDashboardView(request):

    """
    Render All A/B Test List
    :param request:
    :return:
    """

    # Make sure only staff can access this page
    if not request.user.is_staff:
        raise PermissionDenied('Upss... Maaf, halaman ini hanya untuk staff')
    else:
        abtest_list_dashboard = Design.objects.all().order_by("-is_created")
        template = "app_abtest/dashboard/abtest_dashboard_list.html"
        paginator = Paginator(abtest_list_dashboard, 3)
        page = request.GET.get('page', 1)
        try:
            abtest_list_dashboard = paginator.page(page)
        except PageNotAnInteger:
            abtest_list_dashboard = paginator.page(1)
        except EmptyPage:
            abtest_list_dashboard = paginator.page(paginator.num_pages)
        context = {
            'abtest_list_dashboard': abtest_list_dashboard,
        }
        return render(request, template, context)


@login_required
def ABTestDetailDashboardView(request, pk):

    """
    Render Single A/B Test with Stats
    :param request:
    :param pk:
    :return:
    """
    
    if not request.user.is_staff:
        raise Http404("Page does not exist")
    abtest = Design.objects.get(pk=pk)
    abtest_results = DesignComment.objects.filter(design_abtest_title=abtest.id)
    template = "app_abtest/dashboard/abtest_dashboard_detail.html"
    total_ab = DesignComment.objects.filter(design_abtest_title=abtest.id).annotate(num_ab=Count('design_abtest_choice'))
    total_a = DesignComment.objects.filter(design_abtest_title=abtest.id, design_abtest_choice="a").annotate(num_a=Count('design_abtest_choice'))
    total_b = DesignComment.objects.filter(design_abtest_title=abtest.id, design_abtest_choice="b").annotate(num_b=Count('design_abtest_choice'))
    paginator = Paginator(abtest_results, 9)
    page = request.GET.get('page', 1)
    try:
        abtest_results = paginator.page(page)
    except PageNotAnInteger:
        abtest_results = paginator.page(1)
    except EmptyPage:
        abtest_results = paginator.page(paginator.num_pages)
    context = {
        'abtest': abtest, 
        'abtest_results': abtest_results,
        'total_ab': total_ab,
        'total_a': total_a,
        'total_b': total_b
    }
    return render(request, template, context)

# ---------------------------


# TESTER VIEWS -----------------

@login_required
def ABTestDetailTesterView(request, pk):

    """
    Render Single Thread, Comments and Comment Form
    :param request:
    :param pk:
    :return:
    """

    try:
        abtest = Design.objects.get(pk=pk)
    except Design.DoesNotExist:
        raise Http404("Test does not exist")

    form = ABTestCommentModelForm(request.POST)
    template = "app_abtest/tester/abtest_tester_detail.html"
    context = {'abtest': abtest, 'form': form}
    if abtest.is_published != True and not request.user.is_staff:
        raise Http404("Page does not exist")
    if request.method == "POST":
        # yesterday = timezone.now() - timezone.timedelta(days=1)
        form = ABTestCommentModelForm(request.POST)
        if form.is_valid():
            result = form.save(commit = False)
            result.design_abtest_title = Design.objects.get(design_title=abtest.design_title)
            result.design_abtest_tester_user = Tester.objects.get(user=request.user)
            result.design_abtest_tester_email = request.user.email
            result.is_created = datetime.now()
            result.abtest = abtest
            result.save()
            return HttpResponseRedirect('/thanks/') #Nanti harus thank you page
    else:
        form = ABTestCommentModelForm()
    return render(request, template, context)

# ---------------------------

app_abtest/templates/app_abtest/dashboard/abtest_dashboard_list.html
{% extends "app_abtest/main/abtest_base.html" %}
{% block title %}A/B Testing Dashboard - MamiUX{% endblock %}
{% load static%}
{% load humanize %}
{% block content %}

    <!-- A/B TEST DASHBOARD LIST -->
    <!-- Include Doodle -->
    {% include "app_abtest/partials/_doodle.html" %}
    <!--EOC-->
    <div class="mu-ab-dashboard-wrapper">
        <section id="Search Form">
            <div class="mu-dashboard-search-wrapper">
                <div class="mu-container">
                    <div class="columns is-mobile">
                        <div class="column is-12">
                            <div class="mu-dashboard-search-content">
                                <div class="field">
                                    <p class="control has-icons-left">
                                        <input class="input is-large mu-input" type="text" placeholder="What are you looking for?">
                                        <span class="icon is-small is-left">
                                            <i data-feather="search"></i>
                                        </span>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section id="Heading & Button">
            <div class="mu-dashboard-heading-wrapper">
                <div class="mu-container">
                    <div class="columns">
                        <div class="column is-6">
                            <h2>
                                <span class="">🍌</span>
                                <span>MamiUX Dashboard</span>
                            </h2>
                        </div>
                        <div class="column is-6">
                            <span class="mu-feather-icon">Welcome back, <strong style="text-transform: capitalize;">{{ request.user }}</strong></span>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section id="Table Result">
            <div class="mu-ab-card-wrapper">
                <div class="mu-container">
                    <div class="columns is-centered is-multiline">
                        {% for abtest in abtest_list_dashboard %}
                        <div class="column is-4">
                            <a href="{% url 'abtest:abtest_results' pk=abtest.pk %}">
                                <div class="mu-ab-card-item-box">
                                    <div class="mu-ab-card-content">
                                        {% if abtest.is_published %}
                                        <div class="mu-ab-card-ispublished">
                                            <span>PUBLISHED</span>
                                        </div>
                                        {% else %}
                                        <div class="mu-ab-card-notpublished">
                                            <span>NOT PUBLISHED</span>
                                        </div>
                                        {% endif %}
                                        <div class="mu-ab-card-title">                                
                                            <h3>{{ abtest.design_title }}</h3>
                                        </div>
                                        <div class="mu-ab-card-date">
                                            <p>{{ abtest.is_created|naturalday }}</p>
                                        </div>
                                        <p><i data-feather="more-horizontal"></i></p>
                                    </div>
                                </div>
                            </a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>
        <section id="Pagination">
            <div class="mu-pagination-wrapper">
                <nav class="pagination is-centered" role="navigation" aria-label="pagination">
                    {% if abtest_list_dashboard.has_other_pages %}
                        <ul class="pagination-list">
                            {% if abtest_list_dashboard.has_previous %}
                                <li>
                                    <a
                                        href="?page={{ abtest_list_dashboard.previous_page_number }}"
                                        class="pagination-previous">&laquo;
                                    </a>
                                </li>
                            {% else %}
                                <li class="pagination-ellipsis">
                                    <span>&laquo;</span></li>
                            {% endif %}
                            {% for i in abtest_list_dashboard.paginator.page_range %}
                                {% if abtest_list_dashboard.number == i %}
                                    <li class="pagination-link is-current">
                                        <span>{{ i }}
                                            <span class="sr-only">(current)</span>
                                        </span>
                                    </li>
                                {% else %}
                                    <li>
                                        <a href="?page={{ i }}" class="pagination-link">{{ i }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                            {% if abtest_list_dashboards.has_next %}
                                <li>
                                    <a href="?page={{ abtest_list_dashboard.next_page_number }}" class="pagination-next">&raquo;</a>
                                </li>
                            {% else %}
                                <li class="pagination-ellipsis">
                                    <span>&raquo;</span>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            </div>
        </section>
    </div>
        <!-- EOL -->
    {% endblock %}